version: '3.8'
services:
  resource-service:
    container_name: resource-service
    image: com.mycom/resource-service:0.0.1
    ports:
      - 8081:8080
    networks:
      - web-facing

networks:
  web-facing:
    external: true
