version: '3.8'
services:
  idp:
    container_name: identity-provider
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    command:
      - start-dev
    networks:
      - web-facing
  opa:
    container_name: open-policy-agent
    image: openpolicyagent/opa:latest
    ports:
      - 8181:8181
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "--log-format=json-pretty"
      - "--set=decision_logs.console=true"
    networks:
      - web-facing

networks:
  web-facing:
    name: web-facing
    driver: bridge