server:
  port: 8085

spring:
  cloud:
    openfeign:
      circuitbreaker.enabled: true
      client:
        config:
          default:
            connectTimeout: 5000 #1 to test retry
            readTimeout: 5000 #1 to test retry
            loggerLevel: basic

#feign:
#  circuitbreaker.enabled: false
#  cache.enabled: false
#  client:
#    config:
#      default:
#        connectTimeout: 10000
#        readTimeout: 5000
#        loggerLevel: basic
#        metrics.enabled: true
#        retryer:
#          maxAttempts: 5
#          periodMs: 10
#          maxPeriodMs: 500
logging:
  level:
    root: INFO
    com.mycom.resourceservice.restclient.AuthServerClient: DEBUG