server:
  port: 8085

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: false               #enabled it delegate to circuitbreaker acts including fallback
      client:
        config:
          default:
            connectTimeout: 10000   #Connection time out in ms (time needed for the TCP handshake)
            readTimeout: 5000       #Read time out in ms (time needed to read data from the socket)
            loggerLevel: basic

#feign:
#  circuitbreaker.enabled: false
#  cache.enabled: false
#  client:
#    config:
#      default:
#        connectTimeout: 10000
#        readTimeout: 5000
#        loggerLevel: basic
#        metrics.enabled: true
#        retryer:
#          maxAttempts: 5
#          periodMs: 10
#          maxPeriodMs: 500
logging:
  level:
    root: INFO
    com.mycom.resourceservice.restclient.AuthServerClient: DEBUG